# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [2840]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [2841]:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [2842]:
# Write your code here:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [2843]:
# Write your code here:
arr = np.ones((3, 3), dtype=bool)

### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [2844]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2845]:
# Write your code here:
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [2846]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2847]:
# Write your code here:
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [2848]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2849]:
# Write your code here:
arr1 = arr.copy()
arr1[arr1 % 2 != 0] = -1
print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [2850]:
# Input — do not modify
arr = np.arange(10)

In [2851]:
# Write your code here:
arr1 = arr.reshape(2,-1)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [2852]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [2853]:
# Write your code here:
arr = np.vstack((a,b))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [2854]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [2855]:
arr = np.hstack((a,b))
print(arr)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [2856]:
# Input — do not modify
a = np.array([1, 2, 3])

In [2857]:
# Write your code here:
a = np.array([1, 2, 3]) # Ensure 'a' is the 1D array for this exercise
arr = np.repeat(a, 3)
arr1 = np.hstack((arr,a,a,a))
print(arr1)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [2858]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [2859]:
# Write your code here:
arr = np.intersect1d(a, b)
print(arr)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [2860]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [2861]:
# Write your code here:
arr = np.setdiff1d(a, b)
print(arr)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [2862]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [2863]:
# Write your code here:
arr = np.where(a == b)
print(arr)

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [2864]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [2865]:
# Write your code here:
arr = a[(a>5) & (a<10)]
print(arr)

[6 9]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [2866]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [2867]:
# Write your code here:
arr = np.vectorize(maxx)
print(arr(a, b))

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [2868]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [2869]:
# Write your code here:
arr = arr[:, [1, 0, 2]]
print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [2870]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [2871]:
# Write your code here:
arr[[1, 2]] = arr[[2, 1]]
print(arr)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [2872]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [2873]:
# Write your code here:
arr = arr[::-1]
print(arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [2874]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [2875]:
# Write your code here:
arr = arr[:, ::-1]
print(arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [2876]:
# Write your code here:
arr = np.random.uniform(5, 10, size=(5, 3))
print(arr)

[[6.42947845 9.26197544 9.87503247]
 [9.42426647 6.79753922 7.99429473]
 [6.77397806 6.70095108 5.89040495]
 [6.18847104 5.22431141 7.52715715]
 [6.88126227 7.964027   8.14970938]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [2877]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [2878]:
np.set_printoptions(precision=3)
print(rand_arr)

[[0.143 0.934 0.946]
 [0.602 0.388 0.363]
 [0.204 0.277 0.247]
 [0.174 0.967 0.957]
 [0.598 0.731 0.34 ]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [2879]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [2880]:
np.set_printoptions(suppress=True, precision=6) # Set precision for general printing too
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [2881]:
# Input — do not modify
a = np.arange(15)

In [2882]:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [2883]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [2884]:
np.set_printoptions(threshold=np.inf) # Use np.inf to display full array
print(a)
# Reset print options to default for subsequent exercises (optional, but good practice)
np.set_printoptions(threshold=1000, edgeitems=3, linewidth=75, suppress=False, precision=8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [2885]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype=None, encoding='utf-8')
print(iris_data[:5])

[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa')]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [2886]:
# Write your code here:
species = np.array([row[4] for row in iris_data])
print(species[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [2887]:
# Write your code here:
iris_2d = np.array([row.tolist()[:4] for row in iris_data], dtype=np.float64)
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [2888]:
# Write your code here:
sepal_length = iris_2d[:, 0]
mean_sepal_length = np.mean(sepal_length)
median_sepal_length = np.median(sepal_length)
std_sepal_length = np.std(sepal_length)

print(f"Mean sepal length: {mean_sepal_length:.2f}")
print(f"Median sepal length: {median_sepal_length:.2f}")
print(f"Standard deviation of sepal length: {std_sepal_length:.2f}")

Mean sepal length: 5.84
Median sepal length: 5.80
Standard deviation of sepal length: 0.83


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [2889]:
# Write your code here:
sepal_length = iris_2d[:, 0]
normalized_sepal_length = (sepal_length - np.min(sepal_length)) / (np.max(sepal_length) - np.min(sepal_length))
print(normalized_sepal_length[:5])

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [2890]:
# Write your code here:
sepal_length = iris_2d[:, 0]
def softmax(x):
    e_x = np.exp(x - np.max(x)) # Subtract max for numerical stability
    return e_x / e_x.sum(axis=0)

softmax_scores = softmax(sepal_length)
print(softmax_scores[:5])

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [2891]:
# Write your code here:
sepal_length = iris_2d[:, 0]
pct_5 = np.percentile(sepal_length, 5)
pct_95 = np.percentile(sepal_length, 95)

print(f"5th percentile of sepal length: {pct_5:.2f}")
print(f"95th percentile of sepal length: {pct_95:.2f}")

5th percentile of sepal length: 4.60
95th percentile of sepal length: 7.25


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [2892]:
# Write your code here:
iris_2d_nan = iris_2d.copy()
n_nan_values = 20

# Generate random row and column indices
np.random.seed(42) # for reproducibility
i = np.random.randint(0, iris_2d_nan.shape[0], size=n_nan_values)
j = np.random.randint(0, iris_2d_nan.shape[1], size=n_nan_values)

iris_2d_nan[i, j] = np.nan

print(iris_2d_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 nan]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [2893]:
# Write your code here:
sepal_length_nan = iris_2d_nan[:, 0]
missing_values_count = np.sum(np.isnan(sepal_length_nan))
missing_values_positions = np.where(np.isnan(sepal_length_nan))[0]

print(f"Number of missing values in sepal length: {missing_values_count}")
print(f"Positions of missing values in sepal length: {missing_values_positions}")

Number of missing values in sepal length: 5
Positions of missing values in sepal length: [ 14  87 106 116 121]


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [2894]:
# Write your code here:
filtered_rows = iris_2d_nan[(iris_2d_nan[:, 2] > 1.5) & (iris_2d_nan[:, 0] < 5.0)]
print(filtered_rows[:5])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [2895]:
# Write your code here:
rows_without_nan = iris_2d_nan[~np.isnan(iris_2d_nan).any(axis=1)]
print(rows_without_nan[:5])

[[5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [2896]:
# Write your code here:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]

correlation = np.corrcoef(sepal_length, petal_length)[0, 1]
print(f"Correlation between sepal length and petal length: {correlation:.2f}")

Correlation between sepal length and petal length: 0.87


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [2897]:
# Write your code here:
has_nan = np.any(np.isnan(iris_2d_nan))
print(f"Does iris_2d_nan have any missing values? {has_nan}")

Does iris_2d_nan have any missing values? True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [2898]:
# Write your code here:
iris_2d_filled = np.nan_to_num(iris_2d_nan, nan=0.0)
print(iris_2d_filled[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0. ]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [2899]:
# Write your code here:
species_unique, species_counts = np.unique(species, return_counts=True)

for s, c in zip(species_unique, species_counts):
    print(f"Species: {s}, Count: {c}")

Species: Iris-setosa, Count: 50
Species: Iris-versicolor, Count: 50
Species: Iris-virginica, Count: 50


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [2900]:
# Write your code here:
petal_length = iris_2d[:, 2]

bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']

# Define conditions based on the bins
conditions = [
    petal_length < bins[1],  # petal_length < 3
    (petal_length >= bins[1]) & (petal_length < bins[2]),  # 3 <= petal_length < 5
    petal_length >= bins[2]   # petal_length >= 5
]

# Use np.select with an explicit string default to avoid the TypeError
petal_length_binned = np.select(conditions, labels, default='unclassified')
print(petal_length_binned[:10])

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [2901]:
# Write your code here:
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]

volume = (np.pi * petal_length * (sepal_length**2)) / 3
iris_2d_with_volume = np.c_[iris_2d, volume]
print(iris_2d_with_volume[:5])

[[ 5.1         3.5         1.4         0.2        38.13265163]
 [ 4.9         3.          1.4         0.2        35.20049849]
 [ 4.7         3.2         1.3         0.2        30.07237208]
 [ 4.6         3.1         1.5         0.2        33.23805027]
 [ 5.          3.6         1.4         0.2        36.65191429]]


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [2902]:
# Write your code here:
species_names = np.array([row[4] for row in iris_data])
unique_species = np.unique(species_names)

# Assign probabilities: setosa (0.5), versicolor (0.25), virginica (0.25)
probabilities = np.array([0.5 if s == 'Iris-setosa' else 0.25 for s in species_names])
probabilities /= probabilities.sum() # Normalize probabilities

sampled_species = np.random.choice(species_names, size=10, p=probabilities)
print(sampled_species)

['Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [2903]:
# Write your code here:
species_names = np.array([row[4] for row in iris_data])
petal_lengths = iris_2d[:, 2]

# Filter for 'Iris-setosa' and get their petal lengths
setosa_petal_lengths = petal_lengths[species_names == 'Iris-setosa']

# Get unique petal lengths and sort them in ascending order
unique_sorted_petal_lengths = np.sort(np.unique(setosa_petal_lengths))

# The second longest is the second to last element if there are at least two unique values
if len(unique_sorted_petal_lengths) >= 2:
    second_longest_petal_length = unique_sorted_petal_lengths[-2]
    print(f"Second longest petal length for Setosa: {second_longest_petal_length:.2f}")
else:
    print("Not enough unique petal lengths for Setosa to determine the second longest.")

Second longest petal length for Setosa: 1.70


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [2904]:
# Write your code here:
sorted_iris_2d = iris_2d[iris_2d[:, 0].argsort()]
print(sorted_iris_2d[:5])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [2905]:
# Write your code here:
petal_length = iris_2d[:, 2]

values, counts = np.unique(petal_length, return_counts=True)
most_frequent_value_index = np.argmax(counts)
most_frequent_petal_length = values[most_frequent_value_index]

print(f"Most frequent petal length: {most_frequent_petal_length:.2f}")

Most frequent petal length: 1.50


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [2906]:
# Write your code here:
petal_width = iris_2d[:, 3]

positions = np.where(petal_width > 1.0)

if len(positions[0]) > 0:
    first_occurrence_position = positions[0][0]
    print(f"Position of first value > 1.0 in petal width: {first_occurrence_position}")
else:
    print("No value greater than 1.0 found in petal width.")

Position of first value > 1.0 in petal width: 50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [2907]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [2908]:
# Write your code here:
a_clipped = np.clip(a, 10, 30)
print(a_clipped)

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [2909]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [2910]:
# Write your code here:
top_5_indices = np.argsort(a)[-5:][::-1]
print(f"Positions of top 5 maximum values: {top_5_indices}")

Positions of top 5 maximum values: [15 10  3  7 18]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [2911]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [2912]:
# Write your code here:
unique_counts_row_wise = []
for row in arr:
    values, counts = np.unique(row, return_counts=True)
    unique_counts_row_wise.append(list(zip(values, counts)))

print(unique_counts_row_wise)

[[(np.int64(1), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(5), np.int64(1)), (np.int64(6), np.int64(1)), (np.int64(8), np.int64(2)), (np.int64(9), np.int64(2))], [(np.int64(1), np.int64(2)), (np.int64(2), np.int64(1)), (np.int64(3), np.int64(3)), (np.int64(5), np.int64(1)), (np.int64(7), np.int64(1)), (np.int64(9), np.int64(1)), (np.int64(10), np.int64(1))], [(np.int64(2), np.int64(3)), (np.int64(4), np.int64(2)), (np.int64(5), np.int64(3)), (np.int64(6), np.int64(1)), (np.int64(8), np.int64(1))], [(np.int64(1), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(4), np.int64(1)), (np.int64(6), np.int64(1)), (np.int64(8), np.int64(2)), (np.int64(9), np.int64(1)), (np.int64(10), np.int64(2))], [(np.int64(1), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(2)), (np.int64(6), np.int64(1)), (np.int64(7), np.int64(1)), (np.int64(8), np.int64(1)), (np.int64(9), np.int64(1))], [(np.int64(1), np.int64(1)), (np.int64(2), np.int64(1)), (np.in

### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [2913]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [2914]:
# Write your code here:
flat_arr = np.concatenate(arr_2d)
print(flat_arr)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.